// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDixn_7tmDKobHBNeekqbguEWSDrTEImI',
    appId: '1:760649121708:android:04a6bb0b2370b63fb20409',
    messagingSenderId: '760649121708',
    projectId: 'pinly-43399',
    databaseURL: 'https://pinly-43399-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pinly-43399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEppTyMe5tKX3iU4dSRTaJgizcZtbCzE',
    appId: '1:760649121708:ios:b6839d228ad55efdb20409',
    messagingSenderId: '760649121708',
    projectId: 'pinly-43399',
    databaseURL: 'https://pinly-43399-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pinly-43399.appspot.com',
    androidClientId: '760649121708-mqvkacjd5sq49rqk3u78slf5srq3o7bs.apps.googleusercontent.com',
    iosClientId: '760649121708-hudk8nddt1d2hiao5vbu7uolkfc5jlrr.apps.googleusercontent.com',
    iosBundleId: 'mn.tuudug.pinlyf',
  );
}
